- packages/app_package_publisher_fir/lib/src/app_package_publisher_fir.dart
- packages/flutter_distributor/bin/command_package.dart
这是一项必要的功能增强✨ ，有助于我们写入环境变量的值作为常量提供给应用程序。
应用场景是打渠道包、环境切换等，比如官方的 `--dart-define=FLUTTER_WEB_USE_SKIA=true` 用于 Flutter Web 启用 Skia
```
flutter_distributor package --help
Usage: flutter_distributor package [arguments]
-h, --help                             Print this usage information.
--platform=<>
--targets=<>
--build-target=<>
--build-flavor=<>
--build-target-platform=<>
--build-export-options-plist=<>
--build-dart-define=<foo=bar>      The corresponding is --dart-define
```
- https://github.com/flutter/flutter/issues/56792
- https://github.com/flutter/flutter/issues/64944
去掉了一个无效的 `dio-error.dart` 的引入，因为 `dio.dart` 已经 `export 'src/dio_error.dart';`
```
flutter_distributor package --platform=android --targets=apk --build-dart-define=APP_CHANNEL=beta  --build-dart-define=APP_SERVER_ENV=prod …
```
> ✨ 增加 --dart-define 的支持

- packages/flutter_app_builder/lib/src/app_builder.dart
this `distribute_options.yaml`
```yaml
...
- name: android
jobs:    
- name: arm
package:
platform: android
target: apk
build_args:
flavor: arm
obfuscate:
split-debug-info: .
...
```
will cause `type 'Null' is not a subtype of type 'String'` issue
```
type 'Null' is not a subtype of type 'String'
#0      AppBuilder.build (package:flutter_app_builder/src/app_builder.dart:38:37)
#1      FlutterAppBuilder.build (package:flutter_app_builder/src/flutter_app_builder.dart:42:26)
#2      FlutterDistributor.package (package:flutter_distributor/src/flutter_distributor.dart:145:40)
#3      FlutterDistributor.release (package:flutter_distributor/src/flutter_distributor.dart:302:49)
```
> fix build_args map entries value may null

- packages/app_package_publisher_fir/lib/src/app_package_publisher_fir.dart
when use a unauthenticated fir accounts, api response doesnt contain code .
```json
{"msg": "没有实名认证不能上传app"}
```
> fix:fir may response without code

- packages/flutter_distributor/CHANGELOG.md
- packages/flutter_distributor/lib/src/flutter_distributor.dart
- packages/flutter_distributor/pubspec.yaml
Replaces the incorrect word "builded" with the correct word "built"
> Version 0.2.4+1: Fix an incorrectly worded message

- README.md
- docs/en/makers/appimage.md
- docs/en/makers/deb.md
- docs/en/makers/exe.md
- docs/en/makers/rpm.md
- docs/zh/makers/appimage.md
- docs/zh/makers/deb.md
- docs/zh/makers/rpm.md
- examples/hello_world/linux/packaging/rpm/make_config.yaml
- packages/flutter_app_packager/lib/src/flutter_app_packager.dart
- packages/flutter_app_packager/lib/src/makers/deb/app_package_maker_deb.dart
- packages/flutter_app_packager/lib/src/makers/deb/make_deb_config.dart
- packages/flutter_app_packager/lib/src/makers/makers.dart
- packages/flutter_app_packager/lib/src/makers/rpm/app_package_maker_rpm.dart
- packages/flutter_app_packager/lib/src/makers/rpm/make_rpm_config.dart
- packages/flutter_distributor/bin/command_package.dart
- packages/flutter_distributor/bin/main.dart
- packages/shell_executor/lib/src/shell_executor.dart
- website/components/MdxPage/Navbar/Navbar.tsx
This PR adds 
- support for popular Linux packaging format [RPM](https://rpm-packaging-guide.github.io/) used in Rhel, Fedora and OpenSuse "Linux distributions"
- Docs for newly added appimage, deb and rpm package formats (en & zh)
- `--flutter-build-args` for passing flutter build arguments easily
> Feat: Linux RPM packaging support 

- packages/flutter_app_packager/lib/src/makers/exe/inno_setup/inno_setup_script.dart
Currently, only `en`, `zh` and `jp` are evaluated properly by the template generator and written to the `.iss` template. Other language codes do not work.
This adds support for all languages that Inno Setup 6.x ships with by default. (Checked with their latest [stable release](https://jrsoftware.org/isdl.php))
> Add template support for all inno setup 6.x default languages

- docs/en/makers/exe.md
Adds documentation on how to use a custom inno setup template. 
I used this for my project and it looks like [the author of this issue](https://github.com/leanflutter/flutter_distributor/issues/100) is trying to do the same.
> Add documentation for custom inno setup template

- packages/flutter_distributor/bin/command_doctor.dart
- packages/flutter_distributor/bin/command_package.dart
- packages/flutter_distributor/bin/command_publish.dart
- packages/flutter_distributor/bin/command_release.dart
- packages/flutter_distributor/bin/command_upgrade.dart
- packages/flutter_distributor/bin/main.dart
- packages/flutter_distributor/lib/src/flutter_distributor.dart
This is a larger set of changes adding the following:
* Help descriptions and values for all command arguments (except some I did not know yet).
* Proper checking of required parameters for a command with error messages.
* Show error output when `release` fails. Currently, it does not output **any** information.
* Fix auto-update, has been commented out by a recent PR (accidentally, I assume?)
Breaking changes:
* Commands now return exit code `1` instead of `0` when a required parameter is missing
There is still some output being lost when using `release` for multiple jobs. @lijy91 if that's ok for you, I'd like to add (in another PR) a `--verbose` / `-v` flag to `flutter_distributor` that automatically passes `--verbose` to flutter commands (where possible) and outputs more information …
> Improve command usability (help texts, null checks, misc)

- packages/flutter_app_packager/lib/src/makers/dmg/make_dmg_config.dart
when build `macos` dmg, `make_config.yaml`'s window size & position have no effect.
this PR fix this.
```yaml
title: some_app
window:
size:
width: 600
height: 128
contents:
- x: 100
y: 64
type: link
path: "/Applications"
- x: 200
y: 64
type: file
path: some_app.app
```
> fix: fix make_dmg_config lost <window> specification

- packages/flutter_app_builder/lib/src/builders/windows/build_windows_result.dart
> Fix: Windows build failing due to invalid path in Flutter v3.16.0 and v3.15.0-pre 

- packages/flutter_app_builder/lib/src/commands/flutter.dart
fixed https://github.com/leanflutter/flutter_distributor/issues/151
flutter 3.7 没有 flutterVersion 输出
```
flutter --version --machine 
{
"frameworkVersion": "3.7.12",
"channel": "stable",
"repositoryUrl": "https://github.com/flutter/flutter.git",
"frameworkRevision": "4d9e56e694b656610ab87fcf2efbcd226e0ed8cf",
"frameworkCommitDate": "2023-04-17 21:47:46 -0400",
"engineRevision": "1a65d409c7a1438a34d21b60bf30a6fd5db59314",
"dartSdkVersion": "2.19.6",
"devToolsVersion": "2.20.1",
"flutterRoot": "/Users/zacksleo/flutter"
}
```
> fix: Unhandled exception Null check operator used on a null value

- packages/flutter_app_packager/lib/src/makers/rpm/make_rpm_config.dart
So last PR was not tested properly for RPM when metainfo was not present, now it will work for those apps too.
> [FIX] Don't block rpm build if metainfo not found

- README-ZH.md
- README.md
There is also `direct` but I'm not sure if that's supposed to be there or not.
> Pacman was missing from readme + alphabetical order

- examples/hello_world/distribute_options.yaml
Makes it clear that you can use zip with web too.
Otherwise people might not pickup on that.
> Makes it clear that you can use zip with web too.

- packages/flutter_distributor/lib/src/release.dart
I am using the same `distribute_options.yaml` in multiple locations. I comment out the sections of deploy for what is and isn't relevant. I would like to keep on doing this as it means updating all the repositories is easier. So I instead made the jobs listing null safe so that it would work with "null" / empty yaml lists:
Before:
After:
> This adds some tolerance for commented out distribute_options.yaml sections

- packages/flutter_distributor/lib/src/flutter_distributor.dart
CI wasn't failing when I was running `release`:
This seems to be because `release` isn't rethrowing as per the other commands. Adding resolves the issue:
Before: 
After:
It does make it more verbose (redundantly) and the new stack trace doesn't have formatting.
> Errors aren't rethrown so they don't get passed to CI, this is inconsistent with other commands.

- packages/flutter_distributor/bin/main.dart
- packages/flutter_distributor/lib/src/flutter_distributor.dart
There is a pause (least for me) as flutter_distributor checks to see if the user is using the most recent. We should tell people what is going on.
> Let users know that a version check is in progress

- packages/flutter_app_packager/lib/src/makers/appimage/app_package_maker_appimage.dart
Before on a `release`:
Afterwards:
> BugFix: Can't release AppImage because filename is supposed to be AppImage rather than appimage.

- website/src/content/docs/makers/appimage.md
1. Use newer application which support musl libc
2. Add link for metadata creator instead specs
3. Add specs for metadata (appstream metainfo)
> Improve appimage page in website

- packages/flutter_app_packager/lib/src/makers/exe/make_exe_config.dart
- website/src/content/docs/makers/exe.md
- website/src/content/docs/zh-hans/makers/exe.md
修复issues [打包windows平台exe格式时，make_config.yaml里面的设置项setup_icon_file如果有值，会报错 #245 ](https://github.com/leanflutter/flutter_distributor/issues/245)
> fix:can not set icon file when packaging windows exe

- docs/.vitepress/config/en.ts
- docs/.vitepress/config/zh.ts
- docs/en/getting-started.md
- docs/en/publishers/appgallery.md
- docs/zh/getting-started.md
- docs/zh/publishers/appgallery.md
- packages/flutter_app_publisher/lib/src/flutter_app_publisher.dart
- packages/flutter_app_publisher/lib/src/publishers/appgallery/app_package_publisher_appgallery.dart
- packages/flutter_app_publisher/lib/src/publishers/appgallery/publish_appgallery_config.dart
- packages/flutter_app_publisher/lib/src/publishers/publishers.dart
- packages/unified_distributor/lib/src/cli/command_publish.dart
Introduce support for publishing to Huawei AppGallery, including the addition of an app ID option in the publish command and updates to the documentation.
> Add AppGallery support for publishing
